package org.realtimemail;

public enum TrustCapability {
  RENDER_HTML,
  RENDER_CSS,
  RENDER_SVG,
  RUN_SCRIPT_SANDBOXED,
  OPEN_URL_USER_GESTURE,
  PAYMENT_REQUEST_USER_GESTURE,
  STORAGE_ISOLATED,
  NETWORK_DOMAIN_ONLY
}
